# Job from R2Devops HUB --> r2devops.io

stages:
  - deployment

pages:
  stage: deployment
  variables:
    PAGES_BUILD_PATH: 'documentation_build/'
  script:
    - if [ "$PAGES_BUILD_PATH" != "public" -a "$PAGES_BUILD_PATH" != "public/" ]; then mv "$PAGES_BUILD_PATH" public; fi
    - if [ ! -d "public" ]; then echo "Nothing to deploy"; exit 1; fi
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
