# Job from R2Devops hub --> r2devops.io

stages:
  - deploy

pages:
  stage: deploy
  variables:
    PAGES_BUILD_PATH: 'website_build/'
  script:
    - if [ "$PAGES_BUILD_PATH" != "public" -a "$PAGES_BUILD_PATH" != "public/" ]; then
    -   if [ -d "public" ]; then rm -rf public; fi
    -   mv "$PAGES_BUILD_PATH" public
    - fi

    - if [ ! -d "public" ]; then echo "Nothing to deploy"; exit 1; fi
  artifacts:
    paths:
      - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'
