# Job from R2Devops hub --> r2devops.io

stages:
  - deploy

kustomize_deploy:
  image: 
    name: line/kubectl-kustomize:${IMAGE_TAG}
    entrypoint: [""]
  stage: deploy
  variables:
    PROJECT_ROOT: "."
    KUBECONFIG: ""
    CHANGE_IMAGE: "true"
    KUSTOMIZATION_DIR: ""
    NAMESPACE: "$KUBE_NAMESPACE"
    POD_NAME: ""
    POD_IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    POD_IMAGE_TAG: ""
    KUSTOMIZE_OPTIONS: ""
    IMAGE_TAG: "1.21.1-4.1.3"
  script:
    # Working directory
    - cd ${PROJECT_ROOT}/${KUSTOMIZATION_DIR}
    # Image tag to use
    - if [ -z ${POD_IMAGE_TAG} ]; then
    -   if [ ! -z ${CI_COMMIT_TAG} ]; then
    -     POD_IMAGE_TAG=${CI_COMMIT_TAG}
    -   else
    -     POD_IMAGE_TAG=${CI_COMMIT_SHA}
    -   fi
    - fi
    - if [ "${CHANGE_IMAGE}" = "true" ]; then
    -   kustomize edit set image ${POD_NAME}=${POD_IMAGE_NAME}:${POD_IMAGE_TAG} | tee -a ../output.log
    - fi
    # Set the namespace
    - kubectl config set-context --current --namespace=$NAMESPACE
    # Deploy
    - kubectl apply -k . $KUSTOMIZE_OPTIONS | tee -a ../output.log


  environment:
      name: ${CI_COMMIT_REF_SLUG}

  artifacts:
    expose_as: "Kustomize job output"
    paths:
      - output.log

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'