# Job from R2Devops hub --> r2devops.io

stages:
  - deploy

kustomize_deploy:
  image: nekottyo/kustomize-kubeval:latest
  stage: deploy
  variables:
    PROJECT_ROOT: "."
    KUBECONFIG: ""
    KUSTOMIZATION_DIR: ""
    NAMESPACE: "$KUBE_NAMESPACE"
    DEPLOYMENT_NAME: ""
    POD_NAME: ""
    IMAGE_NAME: "$CI_REGISTRY_IMAGE"
    IMAGE_TAG: ""
    KUSTOMIZE_OPTIONS: ""


  script:
    # Working directory
    - cd $PROJECT_ROOT
    - if [ -z ${IMAGE_TAG} ]; then
    -   if [ ! -z ${CI_COMMIT_TAG} ]; then
    -     IMAGE_TAG=${CI_COMMIT_TAG}
    -   else
    -     IMAGE_TAG=${CI_COMMIT_SHA}
    -   fi
    - fi
    # Deploy the cluster
    - kubectl apply -k $KUSTOMIZATION_DIR $KUSTOMIZE_OPTIONS >> output.log
    # Set the current namespace
    - kubectl config set-context --current --namespace=$NAMESPACE
    # Set new image
    - kubectl set image deployment/$DEPLOYMENT_NAME ${POD_NAME}=${IMAGE_NAME}:${IMAGE_TAG} >> output.log


  artifacts:
    expose_as: "Kustomize job output"
    paths:
      - output.log

  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'