stages:
  - build
  - production

documentation:
  image:
    name: squidfunk/mkdocs-material:5.2.2
    entrypoint: [""]
  stage: build
  script:
    - for jobs in Jobs/*; do if [ -d ${job} ]; then mkdir -p docs/${job} && cp ${job}/README.md docs/${job}; fi; done
    - for doc in docs/Jobs/*; do if [ -d ${doc} ]; then echo 'collapse: true' > ${doc}/.pages; fi; done
    - mkdocs build -d ./public
  artifacts:
    when: always
    expose_as: "Documentation"
    paths:
    - public/
  except:
    variables:
      - $DOCUMENTATION_DISABLE

pages:
  stage: production
  script:
    - echo 'Deploying on Gitlab pages'
  needs:
    - job: documentation
      artifacts: true
  artifacts:
    paths:
    - public
  only:
    - master
  except:
    variables:
      - $DOCUMENTATION_DISABLE || $PAGES_DISABLE
