stages:
  - static_tests
  - build
  - deployment

ci_linter:
  image: golang:1.15.2-alpine3.12
  stage: static_tests
  script:
    - apk add --no-cache git
    - go get gitlab.com/orobardet/gitlab-ci-linter
    - for JOB_PATH in jobs/*; do
    -   JOB=$(basename ${JOB_PATH})
    -   gitlab-ci-linter ${JOB_PATH}/${JOB}.yml
    - done

documentation:
  image:
    name: squidfunk/mkdocs-material:5.2.2
    entrypoint: [""]
  stage: build
  script:
    - pip3 install -r requirements.txt
    - python3 builder/builder.py
    - mkdocs build -d ./public
  artifacts:
    when: always
    expose_as: "Documentation"
    paths:
    - public/

pages:
  stage: deployment
  script:
    - echo 'Deploying on Gitlab pages'
  needs:
    - job: documentation
      artifacts: true
  artifacts:
    paths:
    - public
  rules:
    - if: '$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH'

release:
  image: dwdraju/alpine-curl-jq
  stage: deployment
  variables:

  script:
    - curl -s -D "/dev/null" https://gitlab.com/api/v4/projects/go2scale%2Fhub/releases/test} | jq -r ".message"
    - curl -s -D "/dev/null" https://gitlab.com/api/v4/projects/go2scale%2Fhub/releases/test2} | jq -r ".message"
    - for JOB in jobs/*; do
    -   for VERSION in jobs/${JOB}/versions/*; do
    -     if [[ ! $(curl -s -D "/dev/null" https://gitlab.com/api/v4/projects/go2scale%2Fhub/releases/${JOB}-${VERSION%.*} | jq -r ".message") =~ "null" ]]; then
    -       echo "no release for this version"
    -     fi
    -   done
    - done
