# ############################
# Go2Scale DevSecOps template
# ############################
#
# Some variables must be defined in your CI/CD settings
# (https://docs.gitlab.com/ee/ci/variables/#creating-a-custom-environment-variable):
#   * DOCKER_AUTH_CONFIG: docker auth configuration to access Go2Scale images
#   * BOT_TOKEN: Secret token of bot user to interact with Gitlab API
#   * TEMPLATES_REPO_PASSWORD: If needed, secret password (or token)
#     with read access to templates repository

image: alpine:latest

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""  # https://gitlab.com/gitlab-org/gitlab-runner/issues/4501
  # Go2Scale global variables
  BOT_USER_ID: '5097980' # TODO: use your own BOT ID
  TEMPLATES_REPO_URL: 'gitlab.com/go2scale/templates.git'
  TEMPLATES_REPO_USER: ''
  GITLAB_URL: $CI_SERVER_URL

stages:
  - code_level
  - build
  - review
  - application_level
  - staging
  - production
  - performance

include:
  # Gitlab AutoDevops
  - template: Jobs/Build.gitlab-ci.yml
  - template: Security/Container-Scanning.gitlab-ci.yml
  - template: Security/SAST.gitlab-ci.yml
  # Go2Scale DevSecOps
  - project: go2scale/jobs
    ref: master # TODO: set a tag here
    file: quality_check.yml
  - project: go2scale/jobs
    ref: master # TODO: set a tag here
    file: helm.yml

unit_tests:
  image: python:3.7-alpine3.10
  stage: test
  before_script:
    - apk add gcc make musl-dev postgresql-dev git linux-headers libmagic jpeg-dev zlib-dev
    - pip install pipenv && pipenv --bare install --dev
  script:
    - make test

container_scanning:
  stage: review
