# Project information
site_name: G2S Hub
site_description: 'Automated templates for your CI/CD Pipelines !'
site_author: 'Go2Scale <cto@go2scale.com>'
site_url: 'https://go2scale.gitlab.io/jobs/'

# Copyright
copyright: 'Copyright &copy; 2020 Go2Scale'

# Repository
repo_name: 'go2scale/jobs'
repo_url: 'https://gitlab.com/go2scale/jobs'

# Navigation
nav:
  - Home: index.md
  - Concept: concept.md
  - Getting started: getting-started.md
  - Pipelines: pipelines.md
  - Jobs: jobs.md
  - Versioning: versioning.md
  - Contributing: contributing.md
  - License: license.md

# Customization
extra:
  social:
  # TODO: update with Go2Scale social networks
    - icon: 'fontawesome/solid/globe'
      link: 'https://go2scale.com/'
    - icon: 'fontawesome/brands/gitlab'
      link: 'https://gitlab.com/go2scale/'
    - icon: 'fontawesome/brands/twitter'
      link: 'https://twitter.com/thomas_boni'
    - icon: 'fontawesome/brands/linkedin'
      link: 'https://www.linkedin.com/company/go2scale/'

# Configuration
theme:
  name: 'material'
  # Color
  palette:
    primary: 'indigo' # choose: https://squidfunk.github.io/mkdocs-material/getting-started/#primary-colors
    accent: 'indigo'
  # Text
  language: 'en'
  direction: 'ltr'
  font:
    text: 'Roboto'
    code: 'Roboto mono'
  # Images
  favicon: 'images/go2scale_white.svg'
  logo: 'images/go2scale_white.svg'

# Extensions (https://squidfunk.github.io/mkdocs-material/extensions/admonition/)
markdown_extensions:
  - admonition # block-styled content (note, idea, warning, ...)
  - codehilite # highlite code syntax
  - footnotes # references in footnotes
  - toc:
      permalink: true # anchor on titles
  # PyMdown extensions (https://squidfunk.github.io/mkdocs-material/extensions/pymdown)
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Plugins (https://squidfunk.github.io/mkdocs-material/plugins/minify-html/)
plugins:
  - search # search input
  - git-revision-date-localized # revision date at the end of pages
  - minify:
      minify_html: true # minification of html
