# Job from g2s hub. See https://go2scale.gitlab.io/hub/ for more informations

documentation:
  image:
    name: squidfunk/mkdocs-material:5.2.2
    entrypoint: [""]
  stage: build
  script:
    - mkdocs build -d ./public
  artifacts:
    when: always
    expose_as: "Documentation"
    paths:
      - public/
  except:
    variables:
      - $DOCUMENTATION_DISABLE
