# Job from R2Devops hub --> r2devops.io

stages:
  - build

mkdocs:
  image:
    name: squidfunk/mkdocs-material:6.1.7
    entrypoint: [""]
  stage: build
  variables:
    MKDOCS_OUTPUT_PATH: 'website_build/'
  script:
    - pip3 install mkdocs-awesome-pages-plugin==2.4.0
    - pip3 install mkdocs-git-revision-date-localized-plugin==0.7.2
    - pip3 install mkdocs-macros-plugin==0.5.0
    - mkdocs build -d "$MKDOCS_OUTPUT_PATH"
  artifacts:
    when: always
    expose_as: "Mkdocs build"
    paths:
      - "$MKDOCS_OUTPUT_PATH"
      # Below path is a workaround to provide artifact exposition in MR if
      # default output value is used. See https://r2devops.io/jobs/build/mkdocs/#artifacts
      - "website_build/"
