# Job from g2s hub
# See https://go2scale.gitlab.io/jobs/ for more informations

documentation:
  image:
    name: squidfunk/mkdocs-material:5.2.2
    entrypoint: [""]
  stage: build
  script:
    - mkdocs build -d ./public
  artifacts:
    when: always
    expose_as: "Documentation"
    paths:
    - public/
  except:
    variables:
      - $DOCUMENTATION_DISABLE

pages:
  stage: production
  script:
    - echo 'Deploying on Gitlab pages'
  needs:
    - job: documentation
      artifacts: true
  artifacts:
    paths:
   - public
  only:
    - master
  except:
    variables:
      - $DOCUMENTATION_DISABLE || $PAGES_DISABLE
