# Job from R2Devops hub --> r2devops.io

stages:
  - build

mkdocs:
  image:
    name: squidfunk/mkdocs-material:6.1.5
    entrypoint: [""]
  stage: build
  variables:
    MKDOCS_OUTPUT_PATH: 'documentation_build/'
  script:
    - pip3 install mkdocs-git-revision-date-localized-plugin==0.7.2
    - pip3 install mkdocs-macros-plugin==0.5.0
  artifacts:
    when: always
    expose_as: "Mkdocs build"
    paths:
      - "$MKDOCS_OUTPUT_PATH"
