stages:
  - dynamic_tests

zaproxy:
  image: owasp/zap2docker-stable:2.9.0
  stage: dynamic_tests
  variables:
    ZAP_SCANNERS: ""
    ZAP_CONTEXT: ""
    ZAP_TARGET: "http://app"
    ZAP_REPORT: "${CI_PROJECT_DIR}/zap-report.xml"
  script:
    - zap.sh -cmd -quickurl ${ZAP_TARGET} -quickout ${ZAP_REPORT}
  artifacts:
    paths:
      - $ZAP_REPORT
    expire_in: 30 days
    when: always