stages:
  - dynamic_tests

job_name:
    image: owasp/zap2docker-stable:2.9.0
    stage: dynamic_tests
    variables:
      ZAP_SCANNERS: ""
      ZAP_CONTEXT: ""
    script:
      - if [ ! -z ${ZAP_CONTEXT} ]; then
      -   zap-cli context import ${ZAP_CONTEXT}
      -   if [ ! -z ${ZAP_SCANNERS}]; then
      -     zap-cli quick-scan -s $ {ZAP_SCANNERS} --context-name ${ZAP_CONTEXT} --self-contained --start-options '-config api.disablekey=true' http://app 
      -   else
      -     zap-cli quick-scan --context-name ${ZAP_CONTEXT} --self-contained --start-options '-config api.disablekey=true' http://app
      -   fi
      - else
      -   if [ ! -z ${ZAP_SCANNERS}]; then
      -     zap-cli quick-scan -s $ {ZAP_SCANNERS} --self-contained --start-options '-config api.disablekey=true' http://app 
      -   else
      -     zap-cli quick-scan --self-contained --start-options '-config api.disablekey=true' http://app
      -   fi
      - fi
