stages:
  - dynamic_tests

zaproxy:
    image: owasp/zap2docker-stable:2.9.0
    stage: dynamic_tests
    variables:
      ZAP_OPTIONS: ""
      ZAP_CONTEXT: ""
      ZAP_TARGET: "http://app"
    script:
      - if [ ! -z ${ZAP_CONTEXT} ]; then
      -   if [ ! -z ${ZAP_OPTIONS}]; then
      -     python /zap/zap-full-scan.py -n ${ZAP_CONTEXT} -z ${ZAP_OPTIONS} -t ${ZAP_TARGET}
      -   else
      -     python /zap/zap-full-scan.py -n ${ZAP_CONTEXT} -t ${ZAP_TARGET}
      -   fi
      - else
      -   if [ ! -z ${ZAP_OPTIONS}]; then
      -     python /zap/zap-full-scan.py -z ${ZAP_OPTIONS} -t ${ZAP_TARGET}
      -   else
      -     python /zap/zap-full-scan.py -t ${ZAP_TARGET}
      -   fi
      - fi
