stages:
  - static_tests

gitleaks:
  stage: static_tests
  image:
    name: "zricethezav/gitleaks:v8.6.0"
    entrypoint: [""]
  script:
    - gitleaks detect -v -r gitleaks-report.json
  artifacts:
    expose_as: "gitleaks-report"
    paths: ["gitleaks-report.json"]
    when: always
