stages:
  - tests

gitleaks:
  stage: tests
  image:
    name: zricethezav/gitleaks:${IMAGE_TAG}
    entrypoint: [""]
  variables:
    IMAGE_TAG: "v8.15.0"
  script:
    - gitleaks detect -v -r gitleaks-report.json
  artifacts:
    expose_as: "gitleaks-report"
    paths: ["gitleaks-report.json"]
    when: always
