stages:
  - static_tests

# From https://github.com/pmarlow/ci_secrets/blob/master/example.gitlab-ci.yml

gitleaks:
  image: zricethezav/gitleaks:v6.1.2
  stage: static_tests
  script:
    - if [ ! -z ${CI_MERGE_REQUEST_ID} ]; then
    -   ci_secrets --since origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME --log INFO
    - else
    -   ci_secrets --since $CI_COMMIT_BEFORE_SHA --log INFO
    - fi
