# Job from R2Devops hub --> r2devops.io

stages:
  - tests

python_tox:
  image:
    name: vicamo/pyenv:${IMAGE_TAG}
    entrypoint: [""]

  stage: tests

  variables:
    PROJECT_ROOT: "."
    PYTHON_ENV: ""
    ADDITIONAL_OPTIONS: ""

    IMAGE_TAG: "slim-focal"
  script:
    - cd $PROJECT_ROOT
        # Install tox
    - pip install tox
    - if [[ (${PYTHON_ENV} != "") ]]; then PYTHON_ENV="-e $PYTHON_ENV"; else PYTHON_ENV=""; fi
    - tox $PYTHON_ENV $ADDITIONAL_OPTIONS
