# Job from R2Devops hub --> r2devops.io

stages:
  - build

docusaurus_build:

  image:
    name: node:${IMAGE_TAG}
    entrypoint: [""]

  stage: build

  variables:
    PROJECT_ROOT: "."
    DOCUSAURUS_OUTPUT_PATH: "website_build/"
    IMAGE_TAG: "18-buster"
  script:
    - cd ${PROJECT_ROOT}
    - npm install
    - npm install -s @docusaurus/core @docusaurus/preset-classic
    - npx docusaurus build --out-dir ${CI_PROJECT_DIR}/${DOCUSAURUS_OUTPUT_PATH}

  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/${DOCUSAURUS_OUTPUT_PATH}
