stages:
  - static_tests

sls_scan:
  image: shiftleft/sast-scan:v1.9.29
  stage: static_tests
  variables:
    SLS_TYPE: ""
    STOP_ON_VULN: "false"
    OUTPUT_PATH: "sls_scan_report/"
  script:
    - mkdir "$OUTPUT_PATH"
    - if [ ! -z ${SLS_TYPE} ]; then
    -   scan --build -o "$OUTPUT_PATH" -t ${SLS_TYPE} | tee output
    - else
    -   scan --build -o "$OUTPUT_PATH" | tee output
    - fi
    - if [ ${STOP_ON_VULN} == "true" ]; then
    -   cat output | grep ❌
    -   if [ $? -eq 0 ]; then
    -     exit 1
    -   fi
    - fi
  artifacts:
    when: always
    expose_as: "ShiftLeft security scan"
    paths:
      - "$OUTPUT_PATH"
      # Below path is a workaround to provide artifact exposition in MR if
      # default output value is used. https://r2devops.io/jobs/static_tests/sls_scan/#artifacts
      - "sls_scan_report/"
