# Job from R2Devops hub --> r2devops.io

stages:
  - static_tests

super_linter:
  stage: static_tests
  image:
    name: github/super-linter:v3
    entrypoint: [""]
  script:
    - /action/lib/linter.sh
  after_script:
    - npm install -g tap-junit@${TAP_JUNIT_VERSION}
    - mkdir ${CONVERTED_OUTPUT_FOLDER}
    - cd $OUTPUT_FOLDER
    - for report in *; do
    -     cat $report | tap-junit -p -s "${REPORT_SUITE_TEST_NAME}" > ../${CONVERTED_OUTPUT_FOLDER}/${report}.xml # convert each tap file to junit xml
    -     sed -i 's/\\n/\&#x0a;/g' ../${CONVERTED_OUTPUT_FOLDER}/${report}.xml # encode newlines
    - done
  variables:
    RUN_LOCAL: "true"
    DEFAULT_WORKSPACE: $CI_PROJECT_DIR
    DEFAULT_BRANCH: $CI_DEFAULT_BRANCH
    OUTPUT_FORMAT: "tap"
    OUTPUT_DETAILS: "detailed"
    OUTPUT_FOLDER: "super-linter.report"
    CONVERTED_OUTPUT_FOLDER: "converted-xml.report"
    TAP_JUNIT_VERSION: "4.0.0"
    REPORT_SUITE_TEST_NAME: "super_linter"
  artifacts:
    reports:
      junit: "${CONVERTED_OUTPUT_FOLDER}/*.xml"
    paths:
      - "${CONVERTED_OUTPUT_FOLDER}/"
  allow_failure: true
