stages:
  - tests

php_security_checker:
  image: 
    name: jakzal/phpqa:${IMAGE_TAG}
    entrypoint: [""]
  stage: tests
  variables:
    COMPOSER_PATH: "./composer.lock"
    FORMAT_OUTPUT: ""
    IMAGE_TAG: "php7.4-alpine"
  script:
    - local-php-security-checker  --path="${CI_PROJECT_DIR}/${COMPOSER_PATH}" $FORMAT_OUTPUT