# Job from R2Devops hub --> r2devops.io

stages:
  - tests

cargo_clippy:

  image:
    name: rust:${IMAGE_TAG}
    entrypoint: [""]

  stage: tests

  variables:
    PROJECT_ROOT: "."
    ADDITIONAL_OPTIONS: "-- -W clippy::all"

    IMAGE_TAG: "1.57-buster"
  script:
    - cd ${PROJECT_ROOT}
    - rustup component add clippy
    - cargo clippy ${ADDITIONAL_OPTIONS}
