# Job from r2devops hub --> hub.r2devops.io

stages:
  - review

.helm:
  image:
    name: lachlanevenson/k8s-helm:v3.3.4
    entrypoint: [""]
  variables:
    CHART_PATH: "./charts/$CI_PROJECT_NAME"

    # 2 following variables must be defined in job awaiting
    # https://gitlab.com/gitlab-org/gitlab-runner/-/issues/1809#note_412430651
    VALUES_FILE_PATH: ""
    VALUES_SECRET_FILE_PATH: ""

    REGISTRY: "${CI_REGISTRY_IMAGE}"
    KUBECTL_URL: "https://storage.googleapis.com/kubernetes-release/release/v1.19.3/bin/linux/amd64/kubectl"
    HELMSECRETS_URL: "https://github.com/futuresimple/helm-secrets"
    HELMSECRETS_VERSION: "v2.0.2"
    STABLE_REPO_URL: "https://kubernetes-charts.storage.googleapis.com/"
    HELM_ADDITIONAL_OPTIONS: ""
    ENVIRONMENT: "production"

helm_deploy:
  extends: .helm
  stage: review
  environment:
    name: ${ENVIRONMENT}
    url: https://${CI_ENVIRONMENT_SLUG}.${CI_PROJECT_NAME}.${KUBE_INGRESS_BASE_DOMAIN}/
    on_stop: cleanup_review
  except:
    refs:
      - master
  script:
    - apk add --no-cache curl gnupg git bash
    - curl --output /bin/kubectl ${KUBECTL_URL} && chmod a+x /bin/kubectl
    # Following variables defined must be replaced by job variables as soon as
    # issue #1809 will be closed (see comment in variables section)
    - if [ -z ${VALUES_FILE_PATH} ]; then
      # TODO: it doesn't work, think about uses cases: var empty, custom or
      # default
    -   export VALUES_FILE_PATH="./conf/values/${ENVIRONMENT}.yaml"
    - fi
    - if [ -z ${VALUES_SECRET_FILE_PATH} ]; then
    -   export VALUES_SECRET_FILE_PATH="./conf/values/secrets.${ENVIRONMENT}.yaml"
    - fi
    # End of section to replace
    - if [ ! -z ${VALUES_SECRET_FILE_PATH} ]; then
    -   mkdir ${HELM_HOME}/plugins
    -   helm plugin install $HELMSECRETS_URL --version ${HELMSECRETS_VERSION}
    -   gpg --import "${PGP_PUBLIC}"
    -   gpg --allow-secret-key-import --import "${PGP_PRIVATE}"
    - fi
    - helm repo add stable ${STABLE_REPO_URL}
    - helm repo update
    - if [ -f "${VALUES_PATH}/${VALUES_SECRET_FILE}" ]
    - then
    -     SECRET_OPTION="-f ${VALUES_PATH}/${VALUES_SECRET_FILE}"
    - fi
    - helm secrets upgrade ${CI_PROJECT_PATH_SLUG} ${CHART_PATH}
        --namespace "${KUBE_NAMESPACE}" --install
        -f ${VALUES_PATH}/${VALUES_FILE} ${SECRET_OPTION}
        --set-string image.registry=${REGISTRY}
        --set-string image.tag=${CI_COMMIT_SHA}
        --set-string ingress.hostPrefix="${CI_ENVIRONMENT_SLUG}."
        --set-string gitlab.env=${CI_ENVIRONMENT_SLUG}
        --set-string gitlab.app=${CI_PROJECT_PATH_SLUG}
        ${HELM_ADDITIONAL_OPTIONS}

cleanup_review:
  extends: .helm
  stage: review
  variables:
    GIT_STRATEGY: none
  when: manual
  script:
    - apk add --no-cache curl gnupg git bash
    - curl --output /bin/kubectl ${KUBECTL_URL}
        && chmod a+x /bin/kubectl
        && mkdir ${HELM_HOME}/plugins
        && helm plugin install $HELMSECRETS_URL --version ${HELMSECRETS_VERSION}
    - gpg --import "${PGP_PUBLIC}"
    - gpg --allow-secret-key-import --import "${PGP_PRIVATE}"
    - helm repo add stable ${STABLE_REPO_URL}
    - helm repo update
    - apk add --no-cache findutils
    - helm ls --all --short -n ${KUBE_NAMESPACE} | xargs -L1 helm -n ${KUBE_NAMESPACE} delete
    # - kubectl delete namespace $KUBE_NAMESPACE # TODO: it's forbidden due to user RBAC
  environment:
    name: review/${CI_COMMIT_REF_SLUG}
    action: stop
  allow_failure: true
  except:
    refs:
      - master
