# Job from R2Devops hub --> r2devops.io

stages:
  - build

phpdocumentor:
  image:
    name: phpdoc/phpdoc:${IMAGE_TAG}
    entrypoint: [""]
  stage: build
  variables:
    PHPDOC_OUTPUT: "website_build/"
    PHPDOC_CONFIG_FILE: ""
    PHPDOC_TITLE: ""
    PHPDOC_VERBOSITY: ""
    PHPDOC_TEMPLATE: ""
    PHPDOC_INCLUDE_HIDDEN: "false"
    PHPDOC_IGNORE_SYMLINKS: "false"
    PHPDOC_MARKERS: ""
    PHPDOC_OPTIONS: ""
    PROJECT_ROOT: "/"
    IMAGE_TAG: "3.3"
  script:
    # Define verbosity
    - if [ ! -z "$PHPDOC_VERBOSITY" ]; then export PHPDOC_OPTIONS="-$PHPDOC_VERBOSITY $PHPDOC_OPTIONS"; fi
    # Define template
    - if [ ! -z "$PHPDOC_TEMPLATE" ]; then export PHPDOC_OPTIONS="--template=$PHPDOC_TEMPLATE $PHPDOC_OPTIONS"; fi
    # Include config file
    - if [ ! -z "$PHPDOC_CONFIG_FILE" ]; then export PHPDOC_OPTIONS="--config=$CI_PROJECT_DIR$PHPDOC_CONFIG_FILE $PHPDOC_OPTIONS"; fi
    # Include hidden files
    - if [ ! "$PHPDOC_INCLUDE_HIDDEN" = "true" ]; then export PHPDOC_OPTIONS="--hidden $PHPDOC_OPTIONS"; fi
    # Include if ignore symlinks
    - if [ ! "$PHPDOC_IGNORE_SYMLINKS" = "true" ]; then export PHPDOC_OPTIONS="--ignore-symlinks $PHPDOC_OPTIONS"; fi
    # Include markers
    - if [ ! "$PHPDOC_MARKERS" = "true" ]; then export PHPDOC_OPTIONS="--markers=$PHPDOC_MARKERS $PHPDOC_OPTIONS"; fi
    - /opt/phpdoc/bin/phpdoc -t ${PHPDOC_OUTPUT} -d ${CI_PROJECT_DIR}${PROJECT_ROOT} --title="$PHPDOC_TITLE" ${PHPDOC_OPTIONS}
  artifacts:
    when: always
    expose_as: "PHPDoc Build"
    paths:
      - ${PHPDOC_OUTPUT}
      # Below path is a workaround to provide artifact exposition in MR if
      # default output value is used. See https://r2devops.io/jobs/build/phpdocumentor/#artifacts
      - "website_build/"
