stages:
  - build

maven_build:
  image:
    name: maven:${IMAGE_TAG}
    entrypoint: [""]
  stage: build
  variables:
    ARTIFACTS_DIR: ${CI_PROJECT_DIR}/artifacts
    IMAGE_TAG: "3.6.3-jdk-11"
  script:
      - mkdir -p ${ARTIFACTS_DIR}
      - mvn -B clean install -DartifactsDirectory=${ARTIFACTS_DIR} -DskipTests
  artifacts: 
    when: always
    expose_as: "build"
    paths:
      - "${ARTIFACTS_DIR}"
