stages:
  - deploy

netlify_deploy:
  image: node:18-buster
  stage: deploy
  variables:
    NETLIFY_AUTH_TOKEN: ""
    NETLIFY_SITE_ID: ""
    NETLIFY_BUILD_DIRECTORY: "build"
    NETLIFY_CLI_VERSION: "10.5.0"
  script:
    - npm i -g netlify-cli@${NETLIFY_CLI_VERSION}
    - netlify deploy --site ${NETLIFY_SITE_ID} --auth ${NETLIFY_AUTH_TOKEN} --prod --dir ${NETLIFY_BUILD_DIRECTORY}
