stages:
  - dynamic_tests

newman:
  image: node:15.4.0
  stage: dynamic_tests
  variables:
    NEWMAN_COLLECTION: "postman_collection.json"
    NEWMAN_JUNIT_REPORT: "newman-report.xml"
  script:
    - npm install -g newman newman-reporter-junitfull
    - newman run ${NEWMAN_COLLECTION} -r junitfull --reporter-junitfull-export ${NEWMAN_JUNIT_REPORT} -n 2
  artifacts:
    reports:
      junit: ${NEWMAN_JUNIT_REPORT}
    expire_in: 30 days
